python sardh_1_walkThroughAll.py
python sardh_2_make_Parda_N_Predict_Same_Size_RF.py
python sardh_3_run_rf_comp_graphs.py
python sardh_4_prepare_rf_for_phit_input.py
python sardh_5_phit.py sardh_5_input_1_parda_phit_prepared.dat > sardh_5_output_phit_parda.txt
python sardh_5_phit.py sardh_5_input_2_model_phit_prepared.dat > sardh_5_output_phit_model.txt
python sardh_6_gen_cache_hit_compar_graph.py
